name: learn_loop_app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.10.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  go_router: ^17.1.0
  google_fonts: ^8.0.0
  google_sign_in: ^6.3.0
  supabase_flutter: ^2.12.0
  freezed_annotation: ^3.1.0
  http: ^1.4.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  freezed: ^3.2.3
  riverpod_generator: ^4.0.0
  riverpod_lint: ^3.1.0
  custom_lint: ^0.8.1
  go_router_builder: ^4.1.3

flutter:
  uses-material-design: true
